- name: test playbook
  hosts: all
  become: yes
  tasks:
    - name: just printing using shell
      ansible.builtin.shell: echo "test"
    - name: set host name
      ansible.builtin.shell: set-hostname ansible